export { default as About } from './AboutSection/About'
export { default as Experiences } from './ExperiencesSection/Experiences'
export { default as Projects } from './ProjectsSection/Projects'
export { default as Contact } from './ContactSection/Contact'
export { default as HeroSection } from './HeroSection/'
export { default as Footer } from './Footer'
export { default as NavBar } from './NavBar'
